### PR TITLE
Feat/cfg sorted by

### PR DESCRIPTION
**Pull request by vicsn**
## Motivation

This PR was already approved, but reverted to allow for extra CI and testing: https://github.com/AleoNet/snarkVM/pull/2450

### CODE REVIEW

**Review by Meshiest — APPROVED** [review]
I'd imagine the CI `resource_class` changes are going to be a constant back & forth between Aleo Foundation and Provable. As [CircleCI supports env variables](https://circleci.com/docs/env-vars/), I would recommend configuring a `CI_RESOURCE_PREFIX` environment variable that is `anf/` on AleoNet's CircleCI, and empty on Provable's. @zosorock @vicsn 

The macro change alone looks fine

**Review by gluax — APPROVED** [review]
This looks fine to me, however, if the desire is to speed up the CI here are some other things that could help:
- use `--no-fail-fast` for testing.
- replace `cargo test` with [nextest](https://nexte.st/)
- in the root `Cargo.toml` add some additional dev compilation improvements.
```toml
[profile.dev]
codegen-units = 512
opt-level = 1

# Enable high optimizations for dependencies but not for our code
[profile.dev.package."*"]
opt-level = 3
```
- lastly consider using nightly to test. Will get you a faster build by supplying certain nightly only flags. 
- Use a different linker: the default linker is slow, consider `rust-lld`(via nightly) or `mold` linkers for much improvement.
- Also, consider investing the time in using `default-features = false` or, in general, the minimal features for every crate you import.

**Comment by vicsn** [comment]
> I'd imagine the CI resource_class changes are going to be a constant back & forth between Aleo Foundation and Provable. As CircleCI supports env variables, I would recommend configuring a CI_RESOURCE_PREFIX environment variable that is anf/ on AleoNet's CircleCI, and empty on Provable's. @zosorock @vicsn

Great point. We've been trying to get the environment variable to work, but are encountering issues. I'll connect @robwafle with you to discuss

**Comment by vicsn** [comment]
> if the desire is to speed up the CI here are some other things that could help
Great suggestions, thx! I think there's merits to sticking with stock Rust as much as possible for now, but `[nextest](https://nexte.st/)` and the Cargo.toml updates seem like easy wins which are easy to get buy-in for. Adding them to my TODO for post-mainnet, if others read this and feel inclined feel free to make the PR already

**Comment by vicsn** [comment]
Closing so it can be opened directly to AleoNet

**Pull request closed without merging**
